stages:
  train:
    cmd: python scripts/train.py UNet -E 40
    deps:
    - data/kaggle
    - scripts/train.py
    metrics:
    - metrics.json:
        cache: false
    plots:
    - loss.csv:
        cache: false
    outs:
    - model/UNet.keras
  export:
    cmd: python scripts/export.py UNet
    deps:
    - model/UNet.keras
    outs:
    - model/UNet
