name: CML + DVC + Tensorboard + Cloud

on:
  workflow_dispatch:

jobs:
  train-and-report:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: iterative/setup-cml@v2
      - uses: iterative/setup-dvc@v1
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.x'
      - name: Train model
        env:
          GDRIVE_CLIENT_ID: ${{ secrets.GDRIVE_CLIENT_ID }}
          GDRIVE_CLiENT_SECRET: ${{ secrets.GDRIVE_CLIENT_SECRET }}
        run: |
          pip install -r requirements.txt
          dvc pull
          # Reproduce pipeline if any changes detected in dependencies
          dvc repro

          # Use DVC metrics diff to compare metrics to master
          git fetch --prune --unshallow
          dvc metrics diff --show-md master >> report.md

          # Add figure to report
          dvc plots diff --target loss.csv --show-vega master > vega.json
          vl2png vega.json -s 1.3 > vega.png
          echo '![](./vega.png)' >> report.md
          cml comment create --pr --publish report.md
          
          dvc add model/model.h5
